version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/openldap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/php-fpm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/workspace"
    schedule:
      interval: "weekly"
