<div>
    @can('superadmin')
        <flux:button
            variant="ghost"
            icon="folder-sync"
            wire:click="sync"
            title="__('sync.ldap_title')"
        />
    @endcan
</div>